### ISSUE TITLE
Header Params are not added to headers object  

### ISSUE THREAD

**Issue by Sahlikhouloud** [RedFroggy/swagger2-angular2-materialize#10]
When sending a request with header params exp: "Authorization". The parameter is not included in headers Object.

**My solution:** 
In **/src/app/model/api-parameter.ts**
add new const
` const HEADER_PARAM:string = 'header';`
add new method in ParameterObject class:
```
isHeaderParam():boolean {
        return this.in === HEADER_PARAM;
    }
```
In **/src/app/services/apidoc.service.ts**:
```
operation.parameters.forEach((param:ParameterObject) => {
            if (param.isHeaderParam) headers.set(param.name, param.value.selected);
        });
```

**Comment by michaeldesigaud** [comment]
thanks man! could you please make a pull request ?

Regards,

2016-11-15 17:42 GMT+01:00 Sahlikhouloud notifications@github.com:

**Comment by Sahlikhouloud** [comment]
Done !

**Comment by Sahlikhouloud** [comment]
Done!  but unit test still failing
