### ISSUE TITLE
GET call returns a wrong result when the ResponseMessage is empty 

### ISSUE THREAD

**Issue by wi101** [RedFroggy/swagger2-angular2-materialize#15]
When we send a request and our response message contains an empty list "[]" or an empty content "{}" :
1.  if we send our request for the first time, the content of result message is empty.
 2. otherwise the content of result message contains the last displayed message (the last response or the last ErrorResponse)

**Comment by michaeldesigaud** [comment]
yes indeed, can you make a pull request ?

**Comment by wi101** [comment]
Done
