### ISSUE TITLE
PUT/POST calls accept generated body content only

### ISSUE THREAD

**Issue by mhengelein** [RedFroggy/swagger2-angular2-materialize#6]
When sending an API call with methods PUT/POST, the generated body content is used, even if you change it or insert something else.
When trying to send a body without clicking "Generate" before, the server responds with Code 500.

**Assumption:** Result of "Generate" is sent to server, not actual content of form field.

Example without "Generate":
![swaggeruibodyissue-edit](https://cloud.githubusercontent.com/assets/5737264/19594995/1320962e-9788-11e6-8ce6-122a7d6007b3.png)

**Comment by michaeldesigaud** [comment]
Thx for sharing this. Binding must be broken
