### ISSUE TITLE
autoprefixer is not working

### ISSUE THREAD

**Issue by phra** [RedFroggy/swagger2-angular2-materialize#8]
hi,

you have included autoprefixer correctly (also precss) but you are not loading them in the webpack config. you can look at [this configuration](https://github.com/preboot/angular2-webpack/blob/master/webpack.config.js#L200) to see how to load them.

you have also to declare postcss loader in the chain in [this way](https://github.com/preboot/angular2-webpack/blob/master/webpack.config.js#L112).

cheers!

**Comment by phra** [comment]
why are you ignoring this? i can send a PR if you prefer..

**Comment by michaeldesigaud** [comment]
Yes if you dont mind i prefer

Le 14 nov. 2016 17:57, "Francesco Soncina" notifications@github.com a
écrit :

**Comment by phra** [comment]
[done!](https://github.com/RedFroggy/swagger2-angular2-materialize/pull/9)
